language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
    - pip install -e .
cache: pip
script:
    - py.test
after_success: coveralls
